"""Initial Incisight schema."""
from alembic import op
import sqlalchemy as sa

revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("incidents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("title",sa.String(160),nullable=False),sa.Column("affected_service",sa.String(120),nullable=False),sa.Column("severity",sa.String(5),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("keyterms",sa.JSON(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True)))
    op.create_table("evidence",sa.Column("id",sa.String(36),primary_key=True),sa.Column("incident_id",sa.String(36),sa.ForeignKey("incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("source_name",sa.String(160),nullable=False),sa.Column("source_url",sa.String(500)),sa.Column("excerpt",sa.Text(),nullable=False),sa.Column("retrieved_at",sa.DateTime(timezone=True),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("is_simulated",sa.Boolean(),nullable=False))
    op.create_table("incident_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("incident_id",sa.String(36),sa.ForeignKey("incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(30),nullable=False),sa.Column("summary",sa.String(500),nullable=False),sa.Column("subject",sa.String(120)),sa.Column("claim_value",sa.String(120)),sa.Column("source_type",sa.String(20),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("owner",sa.String(80)),sa.Column("evidence_id",sa.String(36),sa.ForeignKey("evidence.id")),sa.Column("idempotency_key",sa.String(80)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("incident_id","idempotency_key",name="uq_event_idempotency"))
    op.create_table("contradictions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("incident_id",sa.String(36),sa.ForeignKey("incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("earlier_event_id",sa.String(36),sa.ForeignKey("incident_events.id"),nullable=False),sa.Column("later_event_id",sa.String(36),sa.ForeignKey("incident_events.id"),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("resolution_note",sa.String(500)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("earlier_event_id","later_event_id",name="uq_contradiction_pair"))
    op.create_table("stakeholder_updates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("incident_id",sa.String(36),sa.ForeignKey("incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("approved_by",sa.String(80)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for name in ("stakeholder_updates","contradictions","incident_events","evidence","incidents"): op.drop_table(name)
